### ISSUE TITLE
Setup Guide

### ISSUE THREAD

**Issue by Silencedpulse** [sapcc/netapp-api-exporter#8]
I'm a newbie to Prometheus.  How do I integrate this exporter with Prometheus?

**Comment by marktups** [comment]
how can i configure "prometheus.yml" job conf???

**Comment by chuan137** [comment]
Configuring the prometheus is not really what this repo is addressing. I suggest to read the manual on prometheus. Depends on your environment, there are many ways to configure it, but you probably can starts with the canonical config flavor, [static config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#static_config). In production, the exporter is likely to run in a k8s cluster. In that case, you can refer to the section [k8s_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config )on the same page.
