### ISSUE TITLE
Feature request: Flags to choose which metrics are retrieved

### ISSUE THREAD

**Issue by FOTempel** [sapcc/netapp-api-exporter#9]
We're using this exporter for SVM monitoring, using an SVM based account. However, the exporter also tries to collect aggregate data. That's great, but the SVM account doesn't have access to that API and this gives error messages in the Ontap audit logs. It would be great if we could parameterize the metrics to be retrieved from Ontap so we can exclude the aggegrate metrics.

**Comment by chuan137** [comment]
Sorry for the late response. You can now disable the aggregate collector with the option `--no-aggregate`.
